# Generated by Django 4.0.5 on 2022-10-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
