# Generated by Django 4.0.5 on 2022-10-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='group',
            new_name='grouping',
        ),
    ]
